# Generated by Django 3.2.9 on 2021-11-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorcycle_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=500)),
                ('founded', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=9999)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
