# Generated by Django 3.2.9 on 2021-11-17 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211117_0508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motorcycle_model',
            options={},
        ),
    ]
