# Generated by Django 3.2.9 on 2021-11-17 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_motorcycle_model_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle_model',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motorcycle_models', to='main_app.motorcycle_company'),
        ),
    ]
